// <auto-generated />
//
// To parse this JSON data, add NuGet 'Newtonsoft.Json' then do:
//
//    using QuickType;
//
//    var responseObj = ResponseObj.FromJson(jsonString);

namespace APIVerve.API.NobelPrizes
{
    using System;
    using System.Collections.Generic;

    using System.Globalization;
    using Newtonsoft.Json;
    using Newtonsoft.Json.Converters;

    public partial class ResponseObj
    {
        [JsonProperty("status")]
        public string Status { get; set; }

        [JsonProperty("error")]
        public object Error { get; set; }

        [JsonProperty("data")]
        public Data Data { get; set; }
    }

    public partial class Data
    {
        [JsonProperty("count")]
        public long Count { get; set; }

        [JsonProperty("filteredOn")]
        public string[] FilteredOn { get; set; }

        [JsonProperty("nobelPrizes")]
        public NobelPrize[] NobelPrizes { get; set; }
    }

    public partial class NobelPrize
    {
        [JsonProperty("firstName")]
        public string FirstName { get; set; }

        [JsonProperty("lastName")]
        public string LastName { get; set; }

        [JsonProperty("born")]
        public DateTimeOffset Born { get; set; }

        [JsonProperty("died")]
        public DateTimeOffset Died { get; set; }

        [JsonProperty("countryborn")]
        public string Countryborn { get; set; }

        [JsonProperty("countrybornCode")]
        public string CountrybornCode { get; set; }

        [JsonProperty("born city")]
        public string BornCity { get; set; }

        [JsonProperty("diedCountry")]
        public string DiedCountry { get; set; }

        [JsonProperty("diedCountryCode")]
        public string DiedCountryCode { get; set; }

        [JsonProperty("diedCity")]
        public string DiedCity { get; set; }

        [JsonProperty("gender")]
        public string Gender { get; set; }

        [JsonProperty("year")]
        [JsonConverter(typeof(ParseStringConverter))]
        public long Year { get; set; }

        [JsonProperty("category")]
        public string Category { get; set; }

        [JsonProperty("motivation")]
        public string Motivation { get; set; }

        [JsonProperty("organization")]
        public string Organization { get; set; }

        [JsonProperty("organizationCity")]
        public string OrganizationCity { get; set; }

        [JsonProperty("organizationCountry")]
        public string OrganizationCountry { get; set; }
    }
}
